import pickle
    
class user():
    def __init__(self,userID,firstName,surname,simsCode,accessLevel,password):
        self.userID = userID    ##PRIMARY KEY##     ##userID will be generated by the code#100-9999##
        self.firstName = firstName
        self.surname = surname
        self.simsCode = simsCode
        self.accessLevel = accessLevel
        self.password = password

class resource():
    def __init__(self,resourceID,resource_location,resource_type,num_resource):
        self.resourceID = resourceID     ##PRIMARY KEY##
        self.resource_location = resource_location
        self.resource_type = resource_type
        self.num_resource = num_resource

def saveUser(userID,firstName,surname,simsCode,accessLevel,password):
    Users = loadUsers()

    new_User = user(userID,firstName,surname,simsCode,accessLevel,password)  ##formats the data into the user class format##  
    Users.append(new_User)                  ##Appends new users to existing user list##

    fh = open("User_Data.p","wb")           ##The entry should be encrypted##
    pickle.dump(Users,fh)
    fh.close()

def bookingSave():
    fh = open("Bookings.p","wb")
    pickle.dump(booking,fh)
    fh.close()

def lessonSave():
    fh = open("Lessons.p","wb")
    pickle.dump(lesson,fh)
    fh.close()

def resourceSave(resourceID,resource_location,resource_type,num_resource):
    Resources = loadResources()
    
    new_resource = resource(resourceID,resource_location,resource_type,num_resource)
    Resources.append(new_resource)


    fh = open("Resources.p","wb")
    pickle.dump(resource,fh)
    fh.close()


def loadUsers():
    try:
        fh = open("User_Data.p","rb")       ##Loads existing users from file into array##
        Users = pickle.load(fh)
        fh.close()        
    except:
        Users=[]                            ##If file doesnt exist creates new array##
    return Users

def loadBookings():
    fh = open("Booking.p","rb")
    bookings_Loaded = pickle.load(fh)
    fh.close()

def loadLessons():
    fh = open("Lessons.p","rb")
    lessons_Loaded = pickle.load(fh)
    fh.close()

def loadResources():
    try:
        fh = open("Resources.p","rb")
        Resources = pickle.load(fh)
        fh.close()
    except:
        Resources=[]
    return Resources

#Resources = loadResources()
#print(Resources[1].resourceID)
